version: 0.0
os: linux 
files:
  - source: ./*
    destination: /var/www/reporde

hooks:
  ApplicationStart:
    - location: scripts/after_install.sh     
      timeout: 300
      runas: root

#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root

#   BeforeInstall:
#     - location: scripts/before_server 
#       timeout: 300
#       runas: root




